---
title: "functionpractice"
author: "Rachel Lee"
date: "4/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}

library(tidyverse)

cmpst_all = read_csv(file = "/Users/rachellee/Google Drive/Practicum/Data/cmpst_all.csv") %>%
 janitor::clean_names() %>%
 mutate( visit = forcats::fct_relevel(visit, c("Screen", "Baseline", "Week3", "Week6", "Week9", "Week14", "Week24")))

sapply(cmpst_all, class)

```


```{r}


  
  
plot_longitudinal <- function(x_arg , y ) {
  
  pos_affect <- cmpst_all$pos_affect
  neg_affect <- cmpst_all$neg_affect
  ham24tot <- cmpst_all$ham24tot
  madrs_total <- cmpst_all$madrs_total
  visit <- cmpst_all$visit
  hvlt_immed <- cmpst_all$hvlt_immed
  hvlt_discrim <- cmpst_all$hvlt_discrim
  trs_total <- cmpst_all$trs_total
  dssi_si <- cmpst_all$dssi_si
  dssi_ss <- cmpst_all$dssi_ss
  dssi_is <- cmpst_all$dssi_is
  dssi_net <- cmpst_all$dssi_net
  gender <- cmpst_all$gender
  
    print( ggplot(cmpst_all, aes(visit, y)) + geom_point(size = 0.1) + theme(axis.text.x = element_text(size=3), axis.text.y = element_text(size=3), strip.text = element_text(size=3)) +
    theme(
  strip.background = element_blank()) +
    facet_wrap(~patient_id, nrow = 10, ncol = 18) +
    theme(panel.spacing = unit(0.2, "lines")) +
    theme(panel.background = element_rect(fill = "white", colour = "grey50"))
  )


}

plot_longitudinal(patient_id, pos_affect)
ggsave(longplot, plot = last_plot, device = png, path = Users/rachellee/Desktop/practiceplots, width = 20, height = 10, units = "in", dpi = 200, limitsize = TRUE)



```


```{r}



exp_plot = function(var = "usage", ID_filter = ID_filter, plotname = "Plot")
{

  yvals = dat_0[,colnames(dat_0) == var]
  ybreaks = seq(round(min(yvals), digits = -1), round(max(yvals) + 5, digits = -1), by = 10)
    
  png(paste0("Plot/Exploratory/", plotname, ".png"), width = 20, height = 10, units = "in", res = 200)
  print(ggplot(data = dat_0, aes(x = Week, y = !!(as.name(var)), group = as.factor(user_id))) + geom_line() + #geom_point() +
    theme_bw() + theme(legend.position = "none") + facet_wrap(.~user_id, ncol = 10) + labs(x = "", y = "")
  dev.off()
}
```

