---
title: "hyptest"
author: "Rachel Lee"
date: "4/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data}
library(tidyverse)


cmpst_all = read_csv(file = "/Users/rachellee/Google Drive/Practicum/Data/cmpst_all.csv") %>%
 janitor::clean_names() %>%
 mutate( visit = forcats::fct_relevel(visit, c("Screen", "Baseline", "Week3", "Week6", "Week9", "Week14", "Week24")))

str(cmpst_all)

```


```{r outcomeEDA}
#extract ham24tot 
cmpst_ham24tot <- cmpst_all %>%
  select(patient_id, gender, site, visit, ham24tot)

#longitudinal plot of ham24tot
ggplot(cmpst_all, aes(visit, ham24tot, group = patient_id) ) + geom_point() + geom_line()
```


```{r outcomechange}
#calculate changes 

cmpst_ham24tot_delta <- cmpst_ham24tot %>%
 pivot_wider(
   names_from = "visit",
   values_from = "ham24tot",
 ) %>%
  mutate(ham24tot_delta3 = Week3 - Baseline) %>%
  mutate(ham24tot_delta14 = Week14 - Baseline) %>%
  select(patient_id, gender, site, ham24tot_delta3, ham24tot_delta14)

cmpst_ham24tot_delta

```



```{r predictorchange}
cmpst_panas <- cmpst_all %>%
  select(patient_id, gender, site, visit, pos_affect, neg_affect) 

cmpst_panas_pos <- cmpst_panas %>%
  select(patient_id, gender, site, visit, pos_affect)

cmpst_panas_neg <- cmpst_panas %>%
  select(patient_id, gender, site, visit, neg_affect)
```


NEGATIVE AFFECT

```{r predictorchange}
#calculate changes in negative affect

cmpst_neg_affect_delta <- cmpst_panas_neg %>%
 pivot_wider(
   names_from = "visit",
   values_from = "neg_affect",
 ) %>%
  mutate(neg_affect_delta3 = Week3 - Baseline) %>%
  mutate(neg_affect_delta14 = Week14 - Baseline) %>%
  select(patient_id, neg_affect_delta3, neg_affect_delta14)

cmpst_neg_affect_delta

```


Joining datasets

```{r jointdata}

ham24tot_neg_affect =
  left_join(cmpst_ham24tot_delta, cmpst_neg_affect_delta, by = "patient_id")

ham24tot_neg_affect

```

Changes from Baseline to Week3 (NEG AFFECT)

```{r linearmodelweek3}


#plotting change in neg_affect against change in ham24tot
ggplot(ham24tot_neg_affect, aes(neg_affect_delta3, ham24tot_delta3) ) + geom_point() + geom_smooth() + facet_grid(~site)


#fitting the model
fit = lm(ham24tot_delta3 ~ neg_affect_delta3, data = ham24tot_neg_affect)

fit %>%
  broom::tidy() %>%
  knitr::kable(digits =3)


```


Changes from Baseline to Week14 (NEG AFFECT)

```{r linearmodelweek14}


#plotting change in neg_affect against change in ham24tot
ggplot(ham24tot_neg_affect, aes(neg_affect_delta14, ham24tot_delta14) ) + geom_point() + geom_smooth() + facet_grid(~site)


#fitting the model
fit = lm(ham24tot_delta14 ~ neg_affect_delta14, data = ham24tot_neg_affect)

fit %>%
  broom::tidy() %>%
  knitr::kable(digits =3)


```













POSITIVE AFFECT

```{r predictorchange}
#calculate changes in positive affect

cmpst_pos_affect_delta <- cmpst_panas_pos %>%
 pivot_wider(
   names_from = "visit",
   values_from = "pos_affect",
 ) %>%
  mutate(pos_affect_delta3 = Week3 - Baseline) %>%
  mutate(pos_affect_delta14 = Week14 - Baseline) %>%
  select(patient_id, pos_affect_delta3, pos_affect_delta14)

cmpst_pos_affect_delta

```


Joining datasets

```{r jointdata}

ham24tot_pos_affect =
  left_join(cmpst_ham24tot_delta, cmpst_pos_affect_delta, by = "patient_id")

ham24tot_pos_affect

```

Changes from Baseline to Week3 (POS AFFECT)

```{r linearmodelweek3}


#plotting change in neg_affect against change in ham24tot
ggplot(ham24tot_pos_affect, aes(pos_affect_delta3, ham24tot_delta3) ) + geom_point() + geom_smooth() + facet_grid(~site)


#fitting the model
fit = lm(ham24tot_delta3 ~ pos_affect_delta3, data = ham24tot_pos_affect)

fit %>%
  broom::tidy() %>%
  knitr::kable(digits =3)


```


Changes from Baseline to Week14 (POS AFFECT)

```{r linearmodelweek14}


#plotting change in neg_affect against change in ham24tot
ggplot(ham24tot_neg_affect, aes(neg_affect_delta14, ham24tot_delta14) ) + geom_point() + geom_smooth() + facet_grid(~site)


#fitting the model
fit = lm(ham24tot_delta14 ~ neg_affect_delta14, data = ham24tot_neg_affect)

fit %>%
  broom::tidy() %>%
  knitr::kable(digits =3)


```

Comment: inverse trend by site? 

